FROM node:18 

WORKDIR /usr/src/app

COPY server/package*.json ./

RUN npm install 

COPY server .

RUN npm run build 

RUN npx prisma generate 

COPY server/entrypoint.sh /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

RUN apt-get update && apt-get install -y netcat-openbsd && rm -rf /var/lib/apt/lists/*

EXPOSE 4000

ENTRYPOINT ["/usr/src/app/entrypoint.sh"]

CMD [ "node","dist/server.js" ] 
