version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=compiler
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: compiler_ts
    ports:
      - 4001:4000
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock

  
volumes:
  postgres-data:
